spring.application.name=backend
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.pbhdshlyvxvhnmnblnck&password=Saruhasan2001@&preferQueryMode=simple
spring.datasource.username=protgres.pbhdshlyvxvhnmnblnck
spring.datasource.password=Saruhasan2001@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true

# Explicitly set the PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect