server.port=${PORT:8080}
spring.application.name=backend

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?user=postgres.pbhdshlyvxvhnmnblnck&password=Saruhasan2001@&preferQueryMode=simple
spring.datasource.username=postgres.pbhdshlyvxvhnmnblnck
spring.datasource.password=Saruhasan2001@
jwt.secret=9UOqTEwAx76Ng6A97hT1Z206uKT5WPKLOZbMiosqQhL

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
