import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import "@/app/globals.css";
import AuthLoader from "@/components/AuthLoader";
import Providers from "../Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <div className="min-h-full flex flex-col">
        <AuthLoader />
        <div className="flex">
          <div className="flex-1">
            <Sidebar />
          </div>
          <main className="flex-4">{children}</main>
        </div>
      </div>
    </Providers>
  );
}
